### ISSUE TITLE
what's the function 'sub2indc' in generate_undistort_map_radtan.m??

### ISSUE THREAD

**Issue by eatenyt** [daniilidis-group/event_feature_tracking#10]

**Comment by alexzzhu** [comment]
Ah this file can be found here: https://github.com/daniilidis-group/event_feature_tracking/blob/master/EventFeatureTracking/Tracker/sub2indc.m

I'll copy it over to the data folder as well so that this is easier.

**Comment by eatenyt** [comment]
Than'k you !!
