### ISSUE TITLE
Question about tracking process time

### ISSUE THREAD

**Issue by Albert-Yip** [daniilidis-group/event_feature_tracking#6]
Hi, I would like to know how much time would one tracking iteration commonly take?

I thought it would be a real-time implementation but one iteration takes a few seconds on my personal laptop as is shown in the attached picture. I don't know where the problem is and how to run it in real time. The used dataset is the "shapes_6dof" from rpg's event camera datasets.

Thank you for your help.

![iter](https://user-images.githubusercontent.com/39665963/56633772-1845d980-6692-11e9-9420-88adb3d37f0d.png)

**Comment by alexzzhu** [comment]
Depending on your laptop, I would say a few (1-2) seconds per iteration are not out of the question. However, here it looks like it's taking sometimes 200 seconds between iterations, which seems strange. Is the do_parallel param set to true? If so, how many CPU cores do you have available?

**Comment by Albert-Yip** [comment]
Thank you. It was the break point that caused the long run time. It normally takes 1~5 seconds per iteration on my laptop with do_parallel set to true and 4 cores i7.
So I wonder if this approach is able to run in real time with a visual odometry framework (like SVO) using only event camera? And is there any method to improve the run time performance?
Thank you very much!

**Comment by alexzzhu** [comment]
It is possible to achieve realtime performance, although for a modest number of features (~30-50), with a good implementation in C++. I've worked on it on and off over the years, but am still not happy enough with the performance to release the code unfortunately. There are definitely tricks you could use to improve speed as well. The main bottleneck is currently the nearest neighbors search in the EM steps. Either replacing this with a lookup table or a GPU implementation would significantly speed up the entire process.

**Comment by Albert-Yip** [comment]
Thank you very much for your help!
