### ISSUE TITLE
Question about 'multi vehicle stereo event camera' dataset

### ISSUE THREAD

**Issue by dlfksj** [daniilidis-group/event_feature_tracking#8]
Hi, 
First of all, thank you so much for sharing the great dataset :)
But I have a question about it.
I'm not sure is this the right place to ask, however, the dataset project page sent me here. I'm sorry if I was wrong.

I downloaded the hdf5 version of the dataset, and I want to know what '/davis/left/imu' columns point to.
I guess they would be [ax(m/s^2), ay, az, rx(rad/s), ry, rz], but I'm not sure. I can't find out in project site or papers. And what Hz is davis/imu data?

Thanks!

**Comment by alexzzhu** [comment]
Hi,

Thanks for your interest in our dataset. Sorry that this was not more clear, the IMU values were translated from the ROS bags, which used this format: http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Imu.html. Your description is correct.

Regarding the rate of the imu data, you should be able to check this with the imu_ts value in the hdf5 files, which contains the timestamp for each message.

In the future, please submit comments to the mvsec repo: https://github.com/daniilidis-group/mvsec.
